### ISSUE TITLE
Not deployable to the scratch org

### ISSUE THREAD

**Issue by rodolforicojr** [wimvelzeboer/fflib-apex-extensions-samplecode#1]
**Describe the bug**
Not deployable to the scratch org
**To Reproduce**
1. Set up the environment as indicated on README
2. when running the step wich deploys the code to scratch org, it will throw an errors related to missing or incorrect definitions

**Comment by wimvelzeboer** [comment]
@rodolforicojr Thank you for bringing this to my attention. The latest commit should fix the broken dependencies.
